<?php
    $prdcts = [
        // [
        //     'id' => 0,
        //     'link' => '',
        //     'src' => '',
        //     'prdct_nm' => 'BARONG TAGALOG',
        //     'prc' => 1,
        //     'rate' => 1,
        //     'liked' => false,
        //     'in_cart' => false
        //     'babayaran' => false,
        //     'ipapadala' => false,
        //     'parating' => false,
        //     'ibinalik' => false,
        //     'nakuha' => false,
        //     'ikinansela' => false
        // ],
        [
            'id' => 1,
            'link' => 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.tatlerasia.com%2Fstyle%2Ffashion%2Fbarong-tagalog-the-traditional-filipino-mens-attire&psig=AOvVaw3SWkDV9F52lJ6qY8vw2fXl&ust=1726844230602000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJCegJmiz4gDFQAAAAAdAAAAABAR',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1726758220/barong1_y9rx6j.jpg',
            'prdct_nm' => 'BARONG TAGALOG',
            'prc' => 400,
            'rate' => 4.5,
            'liked' => true,
            'in_cart' => true,
            'babayaran' => false,
            'ipapadala' => true,
            'parating' => false,
            'ibinalik' => false,
            'nakuha' => true,
            'ikinansela' => false
        ],
        [
            'id' => 2,
            'link' => 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.hiblaltd.com%2Fproduct%2Fbarong-tagalog-loro-p3-green-cream-embroidery-m%2F&psig=AOvVaw3SWkDV9F52lJ6qY8vw2fXl&ust=1726844230602000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJCegJmiz4gDFQAAAAAdAAAAABAJ',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1726759243/barong2_uq26uc.jpg',
            'prdct_nm' => 'BARONG',
            'prc' => 350,
            'rate' => 4.4,
            'liked' => false,
            'in_cart' => false,
            'babayaran' => true,
            'ipapadala' => false,
            'parating' => false,
            'ibinalik' => false,
            'nakuha' => false,
            'ikinansela' => true
        ],
        [
            'id' => 3,
            'link' => 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fshopee.ph%2FDaster-Pambahay-Dress-LARGE-Size-%2528English-Garden-Blowy-Goldleaf%2529-i.54865243.10508290892&psig=AOvVaw0n2f8P4xgqgmw-H-TRbi5W&ust=1726845788844000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCMiJ8YKoz4gDFQAAAAAdAAAAABAE',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1726759507/daster1_wkhdye.jpg',
            'prdct_nm' => 'Daster pang nanay',
            'prc' => 120,
            'rate' => 4.7,
            'liked' => true,
            'in_cart' => true,
            'babayaran' => false,
            'ipapadala' => false,
            'parating' => true,
            'ibinalik' => false,
            'nakuha' => false,
            'ikinansela' => false
        ],
        [
            'id' => 4,
            'link' => 'https://images.app.goo.gl/jozk8A5PNEpuTSDx9',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755498/colorful-pamaypay-filipino-fan-multicolor-tulay-barong-warehouse_5d87a220-d60e-4228-a1ea-f5963d8ac8b5_b6y1xx.jpg',
            'prdct_nm' => 'Pamaypay na makolay',
            'prc' => 50,
            'rate' => 4.7,
            'liked' => true,
            'in_cart' => true,
            'babayaran' => false,
            'ipapadala' => false,
            'parating' => false,
            'ibinalik' => true,
            'nakuha' => false,
            'ikinansela' => true
        ],
        [
            'id' => 5,
            'link' => 'https://images.app.goo.gl/XdVpeN2MRsKSHwi69',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755497/images_3_v58oyn.jpg',
            'prdct_nm' => 'Pamaypay asorted',
            'prc' => 25,
            'rate' => 4.9,
            'liked' => true,
            'in_cart' => false,
            'babayaran' => false,
            'ipapadala' => false,
            'parating' => false,
            'ibinalik' => false,
            'nakuha' => true,
            'ikinansela' => true
        ],
        [
            'id' => 6,
            'link' => 'https://images.app.goo.gl/uD3B2W1kr6vNDcpA9',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755497/images_4_mziy1t.jpg',
            'prdct_nm' => 'Pamaypay na di kinulayan',
            'prc' => 20,
            'rate' => 4.9,
            'liked' => false,
            'in_cart' => false,
            'babayaran' => false,
            'ipapadala' => true,
            'parating' => false,
            'ibinalik' => true,
            'nakuha' => false,
            'ikinansela' => false
        ],
        [
            'id' => 7,
            'link' => 'https://images.app.goo.gl/oeNK1fa9tNDFFm2a8',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755497/images_5_jk7tvt.jpg',
            'prdct_nm' => 'Bakya simple',
            'prc' => 70,
            'rate' => 3.9,
            'liked' => false,
            'in_cart' => false,
            'babayaran' => false,
            'ipapadala' => true,
            'parating' => false,
            'ibinalik' => false,
            'nakuha' => true,
            'ikinansela' => false
        ],
        [
            'id' => 8,
            'link' => 'https://images.app.goo.gl/sHvx8dLy9DM2KMgVA',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755497/images_6_nguuav.jpg',
            'prdct_nm' => 'Walis Tambo',
            'prc' => 50,
            'rate' => 4.6,
            'liked' => true,
            'in_cart' => false,
            'babayaran' => true,
            'ipapadala' => false,
            'parating' => false,
            'ibinalik' => false,
            'nakuha' => false,
            'ikinansela' => true
        ],
        [
            'id' => 10,
            'link' => 'https://images.app.goo.gl/cSmZyRHAqFoVJatA8',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755498/images_7_irlndl.jpg',
            'prdct_nm' => 'Walis Tambo (bulto)',
            'prc' => 175,
            'rate' => 4.7,
            'liked' => false,
            'in_cart' => true,
            'babayaran' => true,
            'ipapadala' => false,
            'parating' => false,
            'ibinalik' => true,
            'nakuha' => false,
            'ikinansela' => false
        ],
        [
            'id' => 11,
            'link' => 'https://images.app.goo.gl/USToUgY5cuHNopsK6',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755498/images_8_jrcqxg.jpg',
            'prdct_nm' => 'Abaca Walis matibay',
            'prc' => 80,
            'rate' => 4.1,
            'liked' => true,
            'in_cart' => false,
            'babayaran' => true,
            'ipapadala' => false,
            'parating' => true,
            'ibinalik' => false,
            'nakuha' => false,
            'ikinansela' => true
        ],
        [
            'id' => 12,
            'link' => 'https://images.app.goo.gl/fVLdM8pCwgNCZUP17',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755498/images_9_bna55s.jpg',
            'prdct_nm' => 'Dalagang Pilipina kostyum',
            'prc' => 120,
            'rate' => 4.6,
            'liked' => true,
            'in_cart' => false,
            'babayaran' => false,
            'ipapadala' => true,
            'parating' => false,
            'ibinalik' => true,
            'nakuha' => false,
            'ikinansela' => false
        ],
        [
            'id' => 13,
            'link' => 'https://images.app.goo.gl/zkjvPXPDnumeGqpW8',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755500/images_10_lj1hgu.jpg',
            'prdct_nm' => 'Baro\'t saya',
            'prc' => 300,
            'rate' => 3.5,
            'liked' => false,
            'in_cart' => false,
            'babayaran' => false,
            'ipapadala' => true,
            'parating' => false,
            'ibinalik' => false,
            'nakuha' => true,
            'ikinansela' => false
        ],
        [
            'id' => 14,
            'link' => 'https://images.app.goo.gl/zEoEFDsQ9569A6UX7',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755500/sg-11134201-7rbl7-lphyvpv8ozzrd1_urimz9.jpg',
            'prdct_nm' => 'Baro\'t saya',
            'prc' => 300,
            'rate' => 3.4,
            'liked' => false,
            'in_cart' => false,
            'babayaran' => true,
            'ipapadala' => true,
            'parating' => false,
            'ibinalik' => false,
            'nakuha' => false,
            'ikinansela' => true
        ],
        [
            'id' => 15,
            'link' => 'https://images.app.goo.gl/7g7dsXK5vu4mjk9u8',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755497/images_11_uwqhy2.jpg',
            'prdct_nm' => 'Dibayder Matibay',
            'prc' => 750,
            'rate' => 4.0,
            'liked' => true,
            'in_cart' => false,
            'babayaran' => true,
            'ipapadala' => false,
            'parating' => false,
            'ibinalik' => true,
            'nakuha' => false,
            'ikinansela' => false
        ],
        [
            'id' => 16,
            'link' => 'https://images.app.goo.gl/V2eShgGNTo7eWzhp6',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755497/images_12_jvqsgw.jpg',
            'prdct_nm' => 'Last Supper pinta',
            'prc' => 400,
            'rate' => 5.0,
            'liked' => true,
            'in_cart' => true,
            'babayaran' => false,
            'ipapadala' => true,
            'parating' => false,
            'ibinalik' => false,
            'nakuha' => false,
            'ikinansela' => true
        ],
        [
            'id' => 17,
            'link' => 'https://images.app.goo.gl/NsA6rdWMKTRAb1YK8',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755498/images_13_q68vxb.jpg',
            'prdct_nm' => 'Last Supper carved makintab',
            'prc' => 1000,
            'rate' => 5.0,
            'liked' => true,
            'in_cart' => true,
            'babayaran' => false,
            'ipapadala' => true,
            'parating' => false,
            'ibinalik' => true,
            'nakuha' => false,
            'ikinansela' => false
        ],
        [
            'id' => 18,
            'link' => 'https://images.app.goo.gl/ZYvjNfxnuGaXNUzd7',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755498/NTII_SKH_1196294-001_yxnt2y.jpg',
            'prdct_nm' => 'Last Supper carved',
            'prc' => 1350,
            'rate' => 5.0,
            'liked' => true,
            'in_cart' => false,
            'babayaran' => true,
            'ipapadala' => false,
            'parating' => true,
            'ibinalik' => false,
            'nakuha' => true,
            'ikinansela' => false
        ],
        [
            'id' => 19,
            'link' => 'https://images.app.goo.gl/HpdSMse84JNppLkN6',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755498/images_14_jnv4hs.jpg',
            'prdct_nm' => 'Plantsa',
            'prc' => 10,
            'rate' => 3.2,
            'liked' => false,
            'in_cart' => true,
            'babayaran' => false,
            'ipapadala' => false,
            'parating' => false,
            'ibinalik' => false,
            'nakuha' => true,
            'ikinansela' => true
        ],
        [
            'id' => 20,
            'link' => 'https://images.app.goo.gl/mWcZqx9XS5kZPNF46',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755499/images_15_dmzdjs.jpg',
            'prdct_nm' => 'Pogs asorted',
            'prc' => 20,
            'rate' => 4.8,
            'liked' => true,
            'in_cart' => false,
            'babayaran' => true,
            'ipapadala' => false,
            'parating' => true,
            'ibinalik' => false,
            'nakuha' => false,
            'ikinansela' => false
        ],
        [
            'id' => 21,
            'link' => 'https://images.app.goo.gl/KcUYayjSBxkvvD9j9',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755498/images_16_qrguqe.jpg',
            'prdct_nm' => 'Pogs Amongus',
            'prc' => 25,
            'rate' => 4.7,
            'liked' => true,
            'in_cart' => true,
            'babayaran' => false,
            'ipapadala' => false,
            'parating' => false,
            'ibinalik' => true,
            'nakuha' => true,
            'ikinansela' => false
        ],
        [
            'id' => 22,
            'link' => 'https://images.app.goo.gl/uyM8ogF3PQ1sQn7n8',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755499/images_17_jdx7xv.jpg',
            'prdct_nm' => 'Text',
            'prc' => 10,
            'rate' => 4.7,
            'liked' => true,
            'in_cart' => true,
            'babayaran' => true,
            'ipapadala' => false,
            'parating' => false,
            'ibinalik' => false,
            'nakuha' => true,
            'ikinansela' => false
        ],
        [
            'id' => 23,
            'link' => 'https://images.app.goo.gl/nhRt4X7VnoUYGait9',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755499/images_18_udshau.jpg',
            'prdct_nm' => 'Text isang box',
            'prc' => 40,
            'rate' => 4.7,
            'liked' => true,
            'in_cart' => false,
            'babayaran' => true,
            'ipapadala' => false,
            'parating' => true,
            'ibinalik' => false,
            'nakuha' => false,
            'ikinansela' => true
        ],
        [
            'id' => 24,
            'link' => 'https://images.app.goo.gl/KPX6WDq7FuQctB268',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755499/images_19_mijyo1.jpg',
            'prdct_nm' => 'Paper Doll (apat na balot)',
            'prc' => 70,
            'rate' => 4.8,
            'liked' => true,
            'in_cart' => true,
            'babayaran' => false,
            'ipapadala' => true,
            'parating' => false,
            'ibinalik' => false,
            'nakuha' => true,
            'ikinansela' => false
        ],
        [
            'id' => 25,
            'link' => 'https://images.app.goo.gl/sj2HpLB1SHpjEic9A',
            'src' => 'https://res.cloudinary.com/damtc4g0q/image/upload/v1727755499/images_20_pc4iqb.jpg',
            'prdct_nm' => 'Paper Doll per pack',
            'prc' => 20,
            'rate' => 4.8,
            'liked' => true,
            'in_cart' => true,
            'babayaran' => false,
            'ipapadala' => false,
            'parating' => false,
            'ibinalik' => true,
            'nakuha' => false,
            'ikinansela' => true
        ]
        // [
        //     'id' => 0,
        //     'link' => '',
        //     'src' => '',
        //     'prdct_nm' => '',
        //     'prc' => 1,
        //     'rate' => 1,
        //     'liked' => false,
        //     'in_cart' => false
        // ],
    ];
?>
